06_django/05_ORM_with_View/05_daily/05_daily01/restaurant_management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('restaurants/', include('restaurants.urls'))
]

06_django/05_ORM_with_View/05_daily/05_daily01/restaurants/urls.py
from django.urls import path
from . import views

app_name = 'restaurants'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create' ),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path()
]

06_django/05_ORM_with_View/05_daily/05_daily01/restaurants/models.py
from django.db import models

# Create your models here.
class Restaurant(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    address = models.TextField()
    phone_number = models.TextField()

06_django/05_ORM_with_View/05_daily/05_daily01/restaurants/forms.py
from django import forms
from .models import Restaurant

class RestaurantForm(forms.ModelForm):
    class Meta:
        model = Restaurant
        fields = '__all__'

06_django/05_ORM_with_View/05_daily/05_daily01/restaurants/views.py
from django.shortcuts import render, get_list_or_404, redirect
from .models import Restaurant
from .forms import RestaurantForm

# Create your views here.
def index(request):
    restaurants = Restaurant.objects.all()
    context = {
        'restaurants' : restaurants,
    }
    return render(request, 'restaurants/index.html', context)

def new(request):
    form = RestaurantForm()
    context = {
        'form':form,
    }
    return render(request, 'restaurants/new.html', context)

def create(request):
    form = RestaurantForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect('restaurants:index') 
    context = {
        'form':form,
    }
    return render(request, 'restaurants/new.html', context)

    # name = request.POST.get('name')
    # desciption = request.POST.get('desciption')
    # address = request.POST.get('address')
    # phone_number = request.POST.get('phone_number')
    
    # restaurant = Restaurant(name=name, desciption=desciption,
    #                         address=address, phone_number=phone_number)
    # restaurant.save()
    # return redirect('articles:index')
    
def detail(request, pk):
    restaurant = Restaurant.objects.get(pk=pk)
    context = {
        'restaurant':restaurant,
    }
    return render(request, 'restaurants/detail.html', context)

def edit(request, pk):
    restaurant = Restaurant.objects.get(pk=pk)
    form = RestaurantForm(instance = restaurant)
    context = {
        'restaurant':restaurant,
        'form':form
    }
    return render(request, 'restaurants/edit.html', context)

def update(request):
    pass

06_django/05_ORM_with_View/05_daily/05_daily01/templates/restaurants/detail.html
{% extends "base.html" %}
{% block content %}
<h1>맛집 상세 정보</h1>
<div>
    <p>식당 번호: {{restaurant.pk}}</p>
    <p>식당 이름: {{restaurant.name}}</p>
    <p>식당 설명: {{restaurant.description}}</p>
    <p>식당 위치: {{restaurant.address}}</p>
    <p>전화 번호: {{restaurant.phone_number}}</p>
</div>
<hr>
<a href="{% url "restaurants:edit" restaurant.pk%} ">[UPDATE]</a>
<form action="">
    <input type="submit" value="DELETE">
</form>
<hr>
<a href="{% url "restaurants:index" %}">[BACK]</a>
{% endblock content %}

06_django/05_ORM_with_View/05_daily/05_daily01/templates/restaurants/edit.html
{% extends "base.html" %}
{% block content %}
    <h1>식당 수정 페이지</h1>
    <form action="{% url "restaurants:update" article.pk %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit">
    </form>
    <hr>
{% endblock content %}

06_django/05_ORM_with_View/05_daily/05_daily01/templates/restaurants/index.html
{% extends "base.html" %}
{% block content %}
<h1>맛집 리스트</h1>
<a href="{% url "restaurants:new" %}">[CREATE]</a>

<ul>

    {% for restaurant in restaurants %}
    <li>
        식당의 이름: {{restaurant.name}}
        <ul>
            <li>주소: {{restaurant.address}}</li>
        </ul>
    </li>
    <a href="{% url "restaurants:detail" restaurant.pk%} " >[DETAIL]</a>
    <hr>
    {% endfor %}
</ul>
{% endblock content %}

06_django/05_ORM_with_View/05_daily/05_daily01/templates/restaurants/new.html
{% extends "base.html" %}
{% block content %}
<h1>식당 생성 페이지</h1>
<form action="{% url "restaurants:create" %}" method="POST">
    {% csrf_token %}
    {% comment %} <p>
      <label for="title">식당 이름:</label>
      <input type="text" name ='title' id='title'>
    </p>
    <p>
        <label for="desciption">식당 설명:</label>
        <input type="desciption" name ='desciption' id='desciption'>
    </p>
    <p>
        <label for="address">식당 주소:</label>
        <textarea name="address" id="address"></textarea>
    </p>
    <p>
        <label for="phone_number">식당 전화번호:</label>
        <textarea name="phone_number" id="phone_number"></textarea>
    </p> {% endcomment %}
    {{form.as_p}}
    <input type="submit" value='CREATE'>
</form>
<a href="{% url "restaurants:index" %}">[BACK]</a>
{% endblock content %}