06_django/09_Auth2/django-authentication-system-skeleton/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name = 'signup'),
    path('delete/', views.delete, name = 'delete'),
    path('update/', views.update, name = 'update'),
    path('change_password/', views.change_password, name ='change_password')
]

06_django/09_Auth2/django-authentication-system-skeleton/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

# 모델폼이니까 !! (모델을 기존 장고에 있었던 auth.user 클래스)
# 해당 모델을 변경하기 위해서 상속 받아서 커스텀을 해줌
class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        
class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email')

06_django/09_Auth2/django-authentication-system-skeleton/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm, CustomUserChangeForm

# Create your views here.
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('articles:index')


def signup(request):
    if request.method == 'POST':
        # 폼에 대한 유효성 검사
        # 유저 인스턴스 생성
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form':form
    }
    return render(request, 'accounts/signup.html', context)

@login_required
def delete(request):
    #  회원 탈퇴
    user = request.user
    user.delete()
    return redirect('articles:index')

@login_required
def update(request):
    # 회원수정 폼 -> 로직
    if request.method =="POST":
        form = CustomUserChangeForm(request.POST, instance = request.user  )
        if form.is_valid():
            form.save()
            return redirect('articles:index')
        return
    else: # GET
        form  = CustomUserChangeForm(instance = request.user )
    context = {
        'form':form
    }
    return render(request, 'accounts/update.html', context)

@login_required
def change_password(request):
    if request.method == 'POST':
        # 비밀번호를 변경 처리하는 로직
        form = PasswordChangeForm(request.user, request.POST)
    else:
        # 비밀번호 변경
        # PasswordChangeForm: 모델폼이 아니므로, 커스텀 해 줄 필요 없음
        form = PasswordChangeForm(request.user)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('articles:index')
    context = {
        'form':form
    }
    return render(request, 'accounts/change_password.html', context)

06_django/09_Auth2/django-authentication-system-skeleton/accounts/templates/accounts/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>비밀번호 변경</h1>
  <form action="{% url "accounts:change_password" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit", value='회원정보 수정'>
  </form>
</body>
</html>

06_django/09_Auth2/django-authentication-system-skeleton/accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>회원가입</h1>
  <form action="{% url "accounts:signup" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit", value='회원가입'>
  </form>
</body>
</html>

06_django/09_Auth2/django-authentication-system-skeleton/accounts/templates/accounts/update.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>회원정보 수정</h1>
  <form action="{% url "accounts:update" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit", value='회원정보 수정'>
  </form>
</body>
</html>